pipeline
{
    agent any
    stages{
        stage('Build Application')
        {
            steps{
                bat "mvn -f java-tomcat-sample/pom.xml clean package"
                echo "done maven part"
            }

            post{
                success{
                    echo "Artifacts archived"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy to Staging')
        {
            steps{
                build job:'Package_deploy_stage'
            }
        }
        stage("Deploy to production")
        {
            steps{
            timeout(time:5,unit:'DAYS')
            {
                input message:"Approve production request ?"
            }
            build job:'Package_deploy_prod'
            }
        }    
    }
}
